### PR TITLE
[hostname] don't enforce RFC1123 compliance on collected hostnames

### PR DESCRIPTION
**Pull request by truthbk**
Adding support for '_' character in more flexible hostname collection. Still report if a hostname isn't RFC1123 compliant though.

### CODE REVIEW

**Comment by olivielpeau** [comment]
any specific reason we should allow supporting `_` in the hostname?
RFC1123 is a long-standing convention on the hostnames of all DD hosts AFAIK.

**Comment by truthbk** [comment]
I had this discussion with @arbll yesterday, I believe other agents will accept underscore and still come up. I should maybe double-check this.

The current behavior of the agent was to print a warning and bail out. If you think we should preserve this behavior, I'm fine with that.

**Comment by olivielpeau** [comment]
Thanks for the explanation!

The current behavior of the Agent on other platforms is indeed to still come up if the `hostname` in `datadog.yaml` is not RFC1123-compliant, however in that case the Agent does not use that hostname at all and instead falls back to other hostname resolution methods (OS-provided hostname, etc). See https://github.com/DataDog/datadog-agent/blob/6.10.2/pkg/util/hostname.go#L115-L122 for example. AFAIK there is no special handling of the underscore `_` character.

I don't have a strong opinion on whether the Agent should bail out when the `hostname` provided in `datadog.yaml` is invalid... One could argue that bailing out sends a more explicit message to users (and is the least-surprising behavior), but on the other hand one could argue that other hostname resolution methods may come up with a reasonable hostname as well so the Agent should still be allowed to come up.

That said, since there isn't any specific behavior related to allowing `_` in hostnames in general, I don't think introducing an edge case here on `_` is a good thing in the long run, and I feel pretty strongly about that :)

**Comment by arbll** [comment]
To add some context, this discussion was started after we noticed the fresh LPAR provisioned for QA had an invalid hostname by default `l0790p020_pub` and that it prevented the agent from starting after a fresh install.

I don't have a strong opinion either on what should be allowed as `hostname` in `datadog.yaml`. However I think we should always have the agent come up if we are able to at least get an hostname from the OS. 

After taking a bit more time to think about this I think we should have the same behaviour as the regular agent and not validate the OS provided hostname is any way. https://github.com/DataDog/datadog-agent/blob/e36980bb9bc7b6efd6841b26f2cd0cff45a89596/pkg/util/hostname.go#L179-L192

**Comment by truthbk** [comment]
Removed the edge case - we validate manual hostnames against RFC1123 but allow non RFC1123-compliant hostnames so long as they're collected from the OS.

**Comment by olivielpeau** [comment]
Thanks for the additional context! If the OS itself provides such a hostname, indeed I don't really see a good way to work around it, so I agree that not validating OS-provided hostnames makes sense.

Not directly related to this PR, but: is there a reason we're using `hostname -s` instead of `hostname` to get the hostname from the OS? https://github.com/DataDog/datadog-unix-agent/blob/6e85269f802705de7855f66331e1a2ead2c67e57/utils/hostname.py#L50
(according to some docs I found https://www.ibm.com/support/knowledgecenter/en/ssw_aix_71/com.ibm.aix.cmds2/hostname.htm, the `-s` flag returns a shorter hostname, whereas we likely want a longer hostname). If there's a reason it'd be nice to document it inline :)

**Comment by truthbk** [comment]
You're absolutely right @olivielpeau, that's a lingering vestige from code borrowed from A5. On linux we'd use `-f` for full linux hostname, as it defaults to the short one. On AIX the default is the fqdn. We never removed the switch after a quick fix and the discrepancy stuck.

**Comment by truthbk** [comment]
It does allow underscores :( definitely a situation that is confirmed by the IBM PDP boxes (they all have underscores in the hostnames).

**Pull request merged**
